version: '3'

services:

  web:
    image: "jveay/tieba-cloud-sign"
    container_name: tieba-cloud-sign
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "false"
    ports:
      - "8888:80"
    networks:
         tieba:
            ipv4_address: 172.19.0.3
    links:
      - db
    depends_on:
      - db
    volumes:
      - /root/tieba:/var/www/html

  db:
    image: "arm64v8/mariadb"
    container_name: tieba-db
    restart: always
    networks:
         tieba:
            ipv4_address: 172.19.0.2
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
    volumes:
      - /srv/dev-disk-by-label-word:/var/lib/mysql

networks:
   tieba:
      ipam:
         config:
         - subnet: 172.19.0.0/16
           gateway: 172.19.0.1