version: '3'
services:

  web:
    image: "jveay/tieba-cloud-sign"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWD: janejane123456
      DB_NAME: tiebacloud
      CSRF: "false"
    ports:
      - "8888:80"
    links:
      - db
    depends_on:
      - db
    volumes:
      - /root/tieba:/var/www/html

  db:
    image: "arm64v8/mariadb"
    restart: always
    environment:
      MYSQL_DATABASE: tiebacloud
      MYSQL_ROOT_PASSWORD: janejane123456
    volumes:
      - /srv/dev-disk-by-label-word:/var/lib/mysql
